#%RAML 1.0

title: P-FleetManagement
description: Process API v1.1 providing the functionality for the capability Management of the Fleet
version: v1
mediaType: application/json

types:
  # D-Car v2.1.0
  ## reused
  VIN:  !include d-car/data_types/entities/value_objects/vin.raml
  ProductionDate: !include d-car/data_types/entities/value_objects/date.raml
  GeoCoordinate: !include d-car/data_types/entities/value_objects/geoCoordinate.raml
  Fuel: !include d-car/data_types/entities/enumerations/fuel.raml
  Consumption: !include d-car/data_types/entities/value_objects/consumption.raml
  ## adapted 
  Car: !include data_types/entities/car.raml
  TechnicalSpecification: !include data_types/entities/value_objects/technicalSpecifications.raml
  DynamicCarData: !include data_types/entities/value_objects/dynamicCarData.raml

  # S-RentalData v1.0.0
  ## adapted
  Rental: !include data_types/entities/rental.raml

annotationTypes:
  monitoringInterval:
    type: integer

/fleets/{fleet_id}/cars:
  uriParameters:
      fleet_id:
        description: Fleet ID
        type: string
  get:
    description: Get overview of all cars assigned to the given fleet
    responses:
      200:
        body:
          type: !include data_types/operations/viewFleetOverview/response.raml
      400:
        description: Requestor is not assigned to fleet with the given fleet id
        body:
          properties:
            message: string
          example:
            message: "Requestor is not assigned to given fleet"
      404:
        description: Could not find the given fleet
        body:
          properties: 
            message: string
          example:
              message: "Could not find the given fleet"
      500:
        body:
          properties:
            message: string
          example:
            message: "Failed to communicate with S-RentalData"

  /{vin}:
      uriParameters:
        vin:
          description: Vehicle Identification Number
          type: string
      post:
        description: Adds the car with the given VIN to the fleet
        body:
          type: !include data_types/operations/addCarToFleet/request.raml
        responses:
          200:
            description: Car has been successfully added to the fleet
            body:
              type: !include data_types/operations/addCarToFleet/response.raml
          400:
            description: Car with the given VIN is already assigned to the fleet or requestor is not assigned to fleet with the given fleet id
            body:
              properties:
                message: string
              examples:
                invalidVIN:
                  message: "A car with the given vin is already assigned to the fleet"
                accessDenied:
                  message: "Requestor is not assigned to given fleet"
          404:
            description: Could not find resources provided in URI path
            body:
              properties:
                message: string
              examples:
                fleetNotFound:
                  message: "Could not find the given fleet"
                carNotFound:
                  message: "Could not find a car with the given vin"
          500:
            body:
              properties:
                message: string
              example: 
                message : "Failed to communicate with D-Car"
      delete:
        description: Remove the car with the given VIN from the fleet 
        responses:
          204:
            description: Car has been successfully removed from the fleet
          400:
            description: Requestor is not assigned to fleet with the given fleet id
            body:
              properties:
                message: string
              example:
                message: "Requestor is not assigned to given fleet"
          404:
            description: Could not find resources provided in URI path
            body:
              properties:
                message: string
              examples:
                fleetNotFound:
                  message: "Could not find the given fleet"
                carNotFound:
                  message: "Could not find a car with the given vin"
          500:
            body:
              properties:
                message: string
              example:
                message : "Failed to communicate with the connected car system"
      get:
        description: Get status of the car with the given VIN assigned to the given fleet
        responses:
          200:
            body:
              type: !include data_types/operations/viewCarStatus/response.raml
          400:
            description: requestor is not assigned to fleet with the given fleet id
            body:
              properties:
                message: string
              example:
                message: "Requestor is not assigned to given fleet"
          404:
            description: Could not find resources provided in URI path
            body:
              properties:
                message: string
              examples:
                fleetNotFound:
                  message: "Could not find the given fleet"
                carNotFound:
                  message: "Could not find a car with the given vin"
          500:
            body:
              properties:
                message: string
              example: 
                message : "Failed to communicate with the connected car system"
