#%RAML 1.0 NamedExample

id: 'fd974d60-02e9-11ed-b939-0242ac120002'
owner: 'mike.manager@csoe.com'
cars: 
    - vin: 'WDD1690071J236589'
      brand: 'Mercedes-Benz'
      model: 'A 180 CDI'
      productionDate: '2005-10-11'
      activeRental: 
        startDate: '2022-06-28T10:00:00'
        endDate: '2022-06-30T10:00:00'
    - vin: '2HNYD18205H500658'
      brand: 'BMW'
      model: 'i3'
      productionDate: '2020-07-27'
