#%RAML 1.0 DataType

description: Dynamic data of a car
type: object
properties:
  fuelLevelPercentage: 
    type: integer
    minimum: 0
    maximum: 100
  position: !include geoCoordinate.raml
  trunkLockState: !include ../enumerations/lockState.raml
  doorsLockState: !include ../enumerations/lockState.raml
  engineState: !include ../enumerations/engineState.raml

example: !include dynamicData_example.raml