#%RAML 1.0 DataType

description: Data about the CO2 emissions of a car as given by the manufacturer
type: object
properties:
  city: 
    type: number
    minimum: 0
  overland:
    type: number
    minimum: 0
  combined:
    type: number
    minimum: 0

example: !include emissions_example.raml