#%RAML 1.0 DataType

description: Data of a car encapsulating the core physical makeup and performance of the car
type: object
properties:
  color: string
  weight: 
    type: integer
    minimum: 0
  trunkVolume:
    type: integer
    minimum: 0
  engine: !include  ../value_objects/engine.raml
  transmission: !include  ../enumerations/transmission.raml
  tire: !include  ../value_objects/tire.raml
  numberOfSeats: 
    type: integer
    minimum: 0
  numberOfDoors:
    type: integer
    minimum: 0
  fuel: !include ../enumerations/fuel.raml
  fuelCapacity: !include ../value_objects/fuelCapacity.raml
  consumption: !include  ../value_objects/consumption.raml
  emissions: !include  ../value_objects/emissions.raml
 
 
example: !include technicalSpecification_example.raml