color: 'blue metallic'
weight: 1320
trunkVolume: 435
engine: !include engine_example.raml
transmission: !include ../enumerations/transmission_example.raml
tire:  !include tire_example.raml
numberOfSeats: 5
numberOfDoors: 3  
fuel: !include ../enumerations/fuel_example.raml
fuelCapacity: !include fuelCapacity_example.raml
consumption: !include consumption_example.raml
emissions: !include emissions_example.raml
  
 
