#%RAML 1.0 DataType

description: A physical unit that serves as the point of contact between a car and the ground
type: object
properties:
  manufacturer: string
  type: !include tireType.raml    

example: !include tire_example.raml