#%RAML 1.0 NamedExample

ex-mercedes:
    vin: 'WDD1690071J236589'
    brand: 'Mercedes-Benz'
    model: 'A 180 CDI'
    productionDate: '2005-10-11'
    technicalSpecifications:
        numberOfSeats: 5
        fuel: DIESEL
        fuelCapacity: '54.0L'
        consumption:
            city: 6.4
            overland: 4.6
            combined: 5.2
    dynamicCarData:
        fuelLevelPercentage: 100
        position: 
            latitude: 42.0
            longitude: 100.0