#%RAML 1.0 DataType
description: Base Attributes of Entity Car

type: object
properties:
  vin: VIN
  brand: string
  model: string
  productionDate: ProductionDate

examples: !include car_base_example.raml