#%RAML 1.0 NamedExample

value:
    vin: 'WDD1690071J236589'
    brand: 'Mercedes-Benz'
    model: 'A 180 CDI'
    productionDate: '2005-10-11'
    technicalSpecification:
      color: 'blue metallic'
      weight: 1320
      trunkVolume: 435
      engine: 
        type: '180 CDI'
        power: 80
      transmission: MANUAL
      tire:
        manufacturer: 'GOODYEAR'
        type: '185/65R15'
      numberOfSeats: 5
      numberOfDoors: 3  
      fuel: !include enumerations/fuel_example.raml
      fuelCapacity: '54.0L' 
      consumption:
        city: 6.4
        overland: 4.6
        combined: 5.2
      emissions:
        city: 137
        overland: 137
        combined: 137
    dynamicData:
      fuelLevelPercentage: 100
      position: 
        latitude: 42.0
        longitude: 100.0
      trunkLockState: UNLOCKED
      doorsLockState: LOCKED
      engineState: ON
 
      